#!/usr/bin/env python3
"""Generate docs/screening-form-spec.md from content/screening.py.

    python tools/export_form_spec.py

The spec is what someone rebuilds the screening in a WordPress form plugin from
(WPForms, Fluent Forms, Gravity Forms). Field names match the wireframe markup, so
answers keep the same keys wherever the form ends up. Re-run after editing screening.py.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "content"))

import leadership  # noqa: E402
import life  # noqa: E402
import screening as S  # noqa: E402

OUT = ROOT / "docs" / "screening-form-spec.md"

CONTACT_FIELDS = [
    ("your_name", "Full name", "Text", "Required"),
    ("your_email", "Email", "Email", "Required"),
    ("your_phone", "Phone", "Phone", "Optional"),
    ("your_contact", "Preferred way to reach you", "Dropdown: Email / Phone call / Text message", "Optional"),
]


def party_rows(n, required):
    need = "Required" if required else "Optional"
    return [
        (f"party{n}_name", f"Party {n} full name", "Text", need),
        (f"party{n}_role", f"Party {n} role", "Dropdown: " + ", ".join(S.ROLES[1:]), "Optional"),
        (f"party{n}_email", f"Party {n} email", "Email", need),
        (f"party{n}_phone", f"Party {n} phone", "Phone", "Optional"),
        (f"party{n}_address", f"Party {n} mailing address", "Text", "Optional"),
    ]


def table(rows, headers):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join([" --- "] * len(headers)) + "|"]
    out += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(out)


def site_section(site, questions, intro):
    lines = [f"## {site['name']}", "",
             f"- **Page:** `/begin-intake/`", f"- **Send responses to:** {site['email']}",
             f"- **Questions:** {len(questions)}", "",
             "### Intro text shown above the form", ""]
    lines += [f"> {p}" for p in intro] + ["", "### Contact fields (before question 1)", "",
                                          table(CONTACT_FIELDS, ["Field name", "Label", "Type", "Required"]), ""]
    lines.append("### Questions\n")
    for i, q in enumerate(questions, start=1):
        if q.get("type") == "parties":
            lines += [f"**{i}. {q['q']}**", "", f"_{q.get('help', '')}_", "",
                      table(party_rows(1, True) + party_rows(2, False),
                            ["Field name", "Label", "Type", "Required"]),
                      "",
                      "| `parties_additional` | Additional parties | Paragraph text | Optional |", ""]
            continue
        lines += [f"**{i}. {q['q']}**", "", f"- Field name: `q{i}` (dropdown, required)",
                  f"- Follow-up field: `q{i}_detail` (paragraph text, shown conditionally)"]
        if q.get("notes"):
            lines.append("- Shown above the dropdown:")
            lines += [f"  - {n.replace('<strong>', '**').replace('</strong>', '**')}" for n in q["notes"]]
        rows = []
        for o in q["options"]:
            if o.get("stop"):
                behaviour = "**STOP — cannot assist.** Show the ineligible notice and referrals."
            elif o.get("detail"):
                behaviour = f"Show `q{i}_detail` labelled “{o['detail']}”" + \
                            (" (required)" if o.get("required") else " (optional)")
            else:
                behaviour = "Continue"
            rows.append([f"`{o['label']}`", o.get("note", "—"), behaviour])
        lines += ["", table(rows, ["Answer", "Guidance shown", "Behaviour"]), ""]
    return "\n".join(lines)


def main():
    doc = f"""# Screening form specification

Generated by `tools/export_form_spec.py` from `content/screening.py` — regenerate rather than
editing by hand.

Use this to rebuild each screening in a WordPress form plugin (WPForms, Fluent Forms, or
Gravity Forms). Keep the field names: they match the wireframe markup, so exported answers stay
consistent wherever the form runs.

## Rules that apply to both sites

1. **Ineligible answers.** Any answer marked **STOP** means the matter cannot be accepted. Show
   the notice “{S.STOP_TITLE}” with the text below, listing the referrals. Let the visitor submit
   anyway so the practice can confirm and reply.
   > {S.STOP_TEXT}
   Referrals: {", ".join(S.STOP_REFERRALS)}.
2. **Conditional follow-ups.** `q<N>_detail` appears only for answers that ask for more, and is
   required where the table says so.
3. **Confidentiality.** Responses include safety, court, and party details. Use encrypted storage,
   restrict who can read entries, set a deletion schedule, and send notifications over TLS. Do not
   forward entries to third-party automation without the owner's agreement.
4. **Confirmation.** Required checkbox: answers are accurate to the best of the visitor's
   knowledge, and every matter is screened before services are offered.
5. **After submit.** Thank-you message confirming a reply will follow, plus the practice's phone
   number for anything urgent.

{site_section(life.SITE, S.LIFE_QUESTIONS, S.LIFE_INTRO)}

{site_section(leadership.SITE, S.LEADERSHIP_QUESTIONS, S.LEADERSHIP_INTRO)}
"""
    OUT.write_text(doc, encoding="utf-8")
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
